name: prueba_task_manager
description: "Aplicación Gestor de Tareas Avanzado"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  
flutter:
  uses-material-design: true
